name = "oogatron"
account_id = "ec2385bbc9929ecbe6a24b00452b3cac"
main = "src/index.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

# Served at https://oogatron.oogaboogax.workers.dev.
workers_dev = true

[observability]
enabled = true

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "oogatron"
database_id = "c0b4f5f5-92eb-4a7e-982f-a72b44934640"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CACHE"
id = "5956cb001dac4b47964cef01a307b583"
