name = "oogatron"
account_id = "1e5c1e8f7c343bf6cabced151b1ae2c6"
main = "src/index.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

# Served at https://oogatron.wickedsmartbitcoin.workers.dev.
workers_dev = true

[observability]
enabled = true

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "oogatron"
database_id = "a4f9fdda-0cff-40fe-94bf-8c54d77dfbee"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CACHE"
id = "6718e4dc7215495ca70e2f18e51ee74d"
